# use the simple server factory if you only want to run on a single port
#server:
#  type: simple
#  connector:
#    type: http
#    port: 8080

server:
  applicationConnectors:
  # see http://www.dropwizard.io/0.9.1/docs/manual/configuration.html#http for more configuration options
    - type: http
      port: 9998
      bindHost: 127.0.0.1 # only bind to loopback
#    - type: https
#      port: 8443
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
#      validatePeers: false
  adminConnectors:
    - type: http
      port: 9997
      bindHost: 127.0.0.1 # only bind to loopback
#    - type: https
#      port: 8444
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
#      validatePeers: false

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.example.app: DEBUG

    # Redirects SQL logs to a separate file
    org.hibernate.SQL:
      level: DEBUG

# Logback's Time Based Rolling Policy - archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}.log.gz
# Logback's Size and Time Based Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
# Logback's Fixed Window Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%i.log.gz

  appenders:
    - type: console
#    - type: file
#      threshold: INFO
#      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
#      currentLogFilename: /var/log/FeedExpander.log
#      archivedLogFilenamePattern: /var/log/FeedExpander-%d{yyyy-MM-dd}-%i.log.gz
#      archivedFileCount: 7
#      timeZone: UTC
#      maxFileSize: 10MB

metrics:
  frequency: 10s

# Define the file that contains all users and password. User and password has to be separated with a single ':' character.
# Leave empty if no authentication is desired.
htusers: htusers

# It is highly recommended to restrict the feeds to be expanded to those you know they're save. Otherwise an 
# attacker can load an own feed which links to something you won't your server have to fetch from the internet.
# Leave empty if no white listing is desired.
feedWhiteList: whitelist.txt

