# use the simple server factory if you only want to run on a single port
#server:
#  type: simple
#  connector:
#    type: http
#    port: 8080

server:
  applicationConnectors:
  # see http://www.dropwizard.io/0.9.1/docs/manual/configuration.html#http for more configuration options
    - type: http
      port: 9998
      bindHost: 127.0.0.1 # only bind to loopback
#    - type: https
#      port: 8443
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
#      validatePeers: false
  adminConnectors:
    - type: http
      port: 9997
      bindHost: 127.0.0.1 # only bind to loopback
#    - type: https
#      port: 8444
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
#      validatePeers: false

# It's possible to specifiy the server name here if it's unwanted to use the name of the host
serverName:

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO


# Logback's Time Based Rolling Policy - archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}.log.gz
# Logback's Size and Time Based Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
# Logback's Fixed Window Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%i.log.gz

  appenders:
    - type: console
#    - type: file
#      threshold: INFO
#      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
#      currentLogFilename: /var/log/FeedExpander.log
#      archivedLogFilenamePattern: /var/log/FeedExpander-%d{yyyy-MM-dd}-%i.log.gz
#      archivedFileCount: 7
#      timeZone: UTC
#      maxFileSize: 10MB

metrics:
  frequency: 10s

# Define the file that contains all users and password. User and password has to be separated with a single ':' character.
# Uncomment and edit htusers file if http auth is required.
# htusers: htusers

# Config file which allows to specify the feeds to be expanded.
feedSites: feed-expander-config.yml

# Config file which allows to specify the pages to be extracted.
pageSites: feed-creator-config.yml

# Cache configuration for loaded web pages linked by feeds.
# Supported cache types are EH_CACHE which needs to have a pageCacheConfigurationFileName which points to a ehcache
# configuration file.
pageCacheType: EH_CACHE
pageCacheConfigurationFileName: ehcache.xml
