feeds:
# alias:
# The alias used as parameter of the expanded url.
# 
# description:  
# The description is only for used for display reasons.
#
# feedUrl:  
# The url to the feed which should be expanded. Currently only http and https are supported.
#
# selector:
# A css selector which is used to identify the part of the web page to be loaded into the feed.
#
# limit:  
# Max number if feed entries to be loaded. Use a low value for feeds which did not get an update too often.
# 
# includeFilter:
# A regular expression which is used to filter feed entries. Each feed entry which matches to this expression 
# will be filtered and not shown in the result feed.
#
# excludeFilter
# A regular expression which is used to filter feed entries. Each feed entry which did not matches to this expression 
# will be filtered and not shown in the result feed. 


- alias: heise
  description: Heise news
  feedUrl: http://www.heise.de/newsticker/heise-atom.xml
  selector: "article"
  limit: 10
  
- alias: golem
  description: Golem news
  feedUrl: http://rss.golem.de/rss.php?feed=RSS2.0
  selector: "article"
  limit: 10
  includeFilter: "(apple|ipad|iphone)"
  excludeFilter: ''
  
- alias: javarevisited
  description: Java revisited
  feedUrl: http://feeds.feedburner.com/Javarevisited
  selector: ".post"
  limit: 10
  
- alias: prolinux
  description: Pro Linux news
  feedUrl: http://pro-linux.de/rss/2/3/rss20_aktuell.xml
  selector: "#news"
  limit: 10
  
- alias: androidpolice
  description: Android Police
  feedUrl: http://feeds.feedburner.com/AndroidPolice
  selector: "[id^=post-]"
  limit: 10
  
- alias: asienspiegel
  description: Asienspiegel
  feedUrl: http://asienspiegel.ch/feed/
  selector: "#content"
  limit: 3
  
- alias: javacodegeeks
  description: Java Code Geeks
  feedUrl: http://feeds.feedburner.com/JavaCodeGeeks
  selector: "article"
  limit: 10
  
- alias: trycatchfinally_opensource
  description: Filtered, open source only feed for "Try catch finally"
  feedUrl: http://blubberbart.blogspot.com/feeds/posts/default
  excludeFilter: opensource
  limit: 10
