feeds:
# alias:
# The alias used as parameter of the expanded url.
# 
# description:  
# The description is only for used for display reasons.
#
# feedUrl:  
# The url to the feed which should be expanded. Currently only http and https are supported.
#
# selector:
# A css selector which is used to identify the part of the web page to be loaded into the feed.
#
# limit:  
# Max number if feed entries to be loaded. Use a low value for feeds which did not get an update too often.
# 
# filter include:
# A case insensitive regular expression which is used to filter feed entries. Each feed entry which matches to this expression 
# will be filtered and not shown in the result feed.
#
# filter exclude:
# A case insensitive regular expression which is used to filter feed entries. Each feed entry which did not matches to this expression 
# will be filtered and not shown in the result feed. 


- alias: heise
  description: News und Foren zu Computer, IT, Wissenschaft, Medien und Politik.
    Preisvergleich von Hardware und Software sowie Downloads bei Heise Medien
  feedUrl: http://www.heise.de/newsticker/heise-atom.xml
  selector: 'article'
  limit: 10
  
- alias: golem
  description: Golem.de - Ständig aktuelle IT-News für Profis und Videos aus Politik,
    Wirtschaft und Wissenschaft über Hardware, Software, Telekommunikation, Games.
  feedUrl: http://rss.golem.de/rss.php?feed=RSS2.0
  selector: 'article'
  limit: 10
  filter:
  - include: '(apple|ipad|iphone)'
    exclude: ''
  
- alias: javarevisited
  description: Java revisited - Tutorials and Interview questions for Java, data 
    structures, algorithms, programming, coding, FIX Protocol, Tibco RV, UNIX, SQL,
    books, certifications.
  feedUrl: http://feeds.feedburner.com/Javarevisited
  selector: '.post'
  limit: 10
  
- alias: prolinux
  description: Magazin mit Schwerpunkten auf Open Source, Android und Linux. 
    Angebote wie News, Artikel, Berichte, Workshops, Tipps, Kalender.
  feedUrl: http://pro-linux.de/rss/2/3/rss20_aktuell.xml
  selector: '#news'
  limit: 10
  
- alias: androidpolice
  description: Android Police - Android News, Apps, Games, Phones, Tablets.
  feedUrl: http://feeds.feedburner.com/AndroidPolice
  selector: '.post-hero,.post-content'
  limit: 10
  
- alias: asienspiegel
  description: Asienspiegel - News aus Japan.
  feedUrl: http://asienspiegel.ch/feed/
  selector: '#content'
  limit: 3
  
- alias: javacodegeeks
  description: JavaCodeGeeks - Learn Java online. Android development tutorials, 
    Java tutorials for beginners, Java books, Scala, Groovy and JRuby news, tutorials, 
    code examples and ...
  feedUrl: http://feeds.feedburner.com/JavaCodeGeeks
  selector: 'article'
  limit: 10
  
- alias: hardwareluxx
  description: Tägliche IT-News, Testberichte über Notebooks, Smartphones, 
    Prozessoren, Grafikkarten und anderen Komponenten rund um PC-Hardware.
  feedUrl: http://www.hardwareluxx.de/index.php/component/obrss/hardwareluxx-rss-feed.feed
  selector: 'div[itemprop=articleBody]'
  limit: 10
  
- alias: trycatchfinally_opensource
  description: Filtered, open source only feed for the "Try catch finally" blog
  feedUrl: http://blubberbart.blogspot.com/feeds/posts/default
  filter:
  - exclude: opensource
  limit: 10
  
- alias: nhk
  description: The latest news from Asia, plus feature stories and special reports 
    from across the region.
  feedUrl: http://www.nhk.or.jp/rss/news/cat0.xml
  selector: '#main > article.module.module--detail'
  limit: 5
  
- alias: only_in_japan
  description: Japan Travel Info Blog | Only in Japan - JNTO
  feedUrl: http://us.jnto.go.jp/blog/feed/
  selector: 'article'
  limit: 5
